from __future__ import annotations


def get_static_events() -> list[dict]:
    return [
        {
            "venue": "Vauxhall City Farm",
            "title": "City Farm Visit",
            "description": "Open daily, free entry, check website for special events",
            "start": None,
            "url": "https://www.vauxhallcityfarm.org/",
            "address": "165 Tyers St, London SE11 5HS",
            "distance": "~45 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Farms & Animals",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Surrey Docks Farm",
            "title": "City Farm Visit",
            "description": "Open daily, free entry, check website for special events",
            "start": None,
            "url": "https://www.surreydocksfarm.org.uk/",
            "address": "Rotherhithe St, London SE16 5ET",
            "distance": "~35 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Farms & Animals",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Kentish Town City Farm",
            "title": "City Farm Visit",
            "description": "Open daily, free entry, check website for special events",
            "start": None,
            "url": "https://ktcityfarm.org.uk/",
            "address": "1 Cressfield Cl, London NW5 4BN",
            "distance": "~55 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Farms & Animals",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Freightliners City Farm",
            "title": "City Farm Visit",
            "description": "Open daily, free entry, check website for special events",
            "start": None,
            "url": "https://freightlinersfarm.org.uk/",
            "address": "Sheringham Rd, London N7 8PF",
            "distance": "~48 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Farms & Animals",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Newham City Farm",
            "title": "City Farm Visit",
            "description": "Open daily, free entry, check website for special events",
            "start": None,
            "url": "https://www.newhamcityfarm.org.uk/",
            "address": "Stansfeld Rd, London E6 5LT",
            "distance": "~30 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Farms & Animals",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Victoria Park Splash Pool",
            "title": "Splash Pad",
            "description": "Open May-September",
            "start": None,
            "url": "https://www.towerhamlets.gov.uk/lgnl/leisure_and_culture/parks_and_open_spaces/Victoria_park.aspx",
            "address": "Victoria Park, London E3",
            "distance": "Local",
            "age": "Toddlers+",
            "cost": "Free",
            "category": "Seasonal",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Clissold Park Splash Pad",
            "title": "Splash Pad",
            "description": "Open May-September",
            "start": None,
            "url": "https://www.hackney.gov.uk/clissold-park",
            "address": "Green Lanes, London N16 9HJ",
            "distance": "~45 mins",
            "age": "Toddlers+",
            "cost": "Free",
            "category": "Seasonal",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Thames Barrier Park Splash Area",
            "title": "Splash Pad",
            "description": "Open May-September",
            "start": None,
            "url": "https://www.royalgreenwich.gov.uk/info/200266/parks/612/thames_barrier_park",
            "address": "North Woolwich Rd, London E16 2HP",
            "distance": "~30 mins",
            "age": "Toddlers+",
            "cost": "Free",
            "category": "Seasonal",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Chingford Miniature Railway",
            "title": "Miniature Railway",
            "description": "Apr-Oct, Sundays",
            "start": None,
            "url": "https://www.e4u.org.uk/chingford-model-engineering-club",
            "address": "Ridgeway Park, London E4",
            "distance": "~35 mins",
            "age": "All ages",
            "cost": "£",
            "category": "Seasonal",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Brockwell Park Miniature Railway",
            "title": "Miniature Railway",
            "description": "Apr-Oct, Sundays",
            "start": None,
            "url": "https://www.brockwell-live.co.uk/miniature-railway",
            "address": "Brockwell Park, London SE24",
            "distance": "~65 mins",
            "age": "All ages",
            "cost": "£",
            "category": "Seasonal",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "London Eye",
            "title": "Permanent Attraction",
            "description": "Book timed slots online",
            "start": None,
            "url": "https://www.londoneye.com/",
            "address": "Riverside Building, County Hall, London SE1 7PB",
            "distance": "~40 mins",
            "age": "All ages",
            "cost": "££",
            "category": "Soft Play & Indoor",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Paradox Museum London",
            "title": "Permanent Attraction",
            "description": "Interactive illusion experiences",
            "start": None,
            "url": "https://paradoxmuseumlondon.com/",
            "address": "90 Brompton Rd, London SW3 1JJ",
            "distance": "~55 mins",
            "age": "All ages",
            "cost": "££",
            "category": "Soft Play & Indoor",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "The Castle Climbing Centre",
            "title": "Family Climbing Sessions",
            "description": "Check website for children slots",
            "start": None,
            "url": "https://www.castle-climbing.co.uk/",
            "address": "Green Lanes, London N4 2HA",
            "distance": "~50 mins",
            "age": "3+",
            "cost": "££",
            "category": "Sports & Swimming",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Young V&A",
            "title": "Interactive Children's Museum",
            "description": "Mudlarks gallery for under-8s, workshops, creative stations. Free entry.",
            "start": None,
            "url": "https://www.vam.ac.uk/young",
            "address": "Cambridge Heath Rd, London E2 9PA",
            "distance": "~15 mins",
            "age": "Under 8s",
            "cost": "Free",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Natural History Museum",
            "title": "Family Activities & Exhibitions",
            "description": "Check What's On for family workshops, trails and exhibitions.",
            "start": None,
            "url": "https://www.nhm.ac.uk/visit/whats-on.html",
            "address": "Cromwell Rd, London SW7 5BD",
            "distance": "~55 mins",
            "age": "All ages",
            "cost": "Free (some events ticketed)",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Tate Modern",
            "title": "Family Activities",
            "description": "Free family workshops weekends and holidays. Check What's On.",
            "start": None,
            "url": "https://www.tate.org.uk/visit/tate-modern/families",
            "address": "Bankside, London SE1 9TG",
            "distance": "~40 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "London Transport Museum",
            "title": "Family Fun Days",
            "description": "Interactive galleries, mini vehicles, themed play zones. Under 18s free.",
            "start": None,
            "url": "https://www.ltmuseum.co.uk/whats-on",
            "address": "Covent Garden Piazza, London WC2E 7BB",
            "distance": "~40 mins",
            "age": "All ages",
            "cost": "Under 18s free",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Museum of the Home",
            "title": "Discovery Garden & Family Days",
            "description": "Rooms Through Time, almshouse tours, free entry.",
            "start": None,
            "url": "https://www.museumofthehome.org.uk/whats-on/",
            "address": "136 Kingsland Rd, London E2 8EA",
            "distance": "~25 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "V&A East Storehouse",
            "title": "V&A Collection Access",
            "description": "NEW 2026! Behind-the-scenes V&A collection, family events.",
            "start": None,
            "url": "https://www.vam.ac.uk/info/va-east",
            "address": "Queen Elizabeth Olympic Park, London E20",
            "distance": "~18 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "London Canal Museum",
            "title": "Canal Boat Trips & Museum",
            "description": "Boat trips through Islington Tunnel, canal history, ice cream heritage.",
            "start": None,
            "url": "https://www.canalmuseum.org.uk/",
            "address": "12-13 New Wharf Rd, London N1 9RT",
            "distance": "~35 mins",
            "age": "All ages",
            "cost": "£9-17",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Museum of Water & Steam",
            "title": "Family Activity Days",
            "description": "Victorian pumping station, splash zone, family workshops.",
            "start": None,
            "url": "https://waterandsteam.org.uk/",
            "address": "Green Dragon Ln, Brentford TW8 0EN",
            "distance": "~70 mins",
            "age": "All ages",
            "cost": "Free (some events ticketed)",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Olympic Park Playground",
            "title": "Tumbling Bay & Inclusive Playground",
            "description": "Sand, water play, giant slides. Free.",
            "start": None,
            "url": "https://www.queenelizabetholympicpark.co.uk/",
            "address": "Queen Elizabeth Olympic Park, London E20",
            "distance": "~18 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Outdoor & Parks",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Mile End Play Pavilion",
            "title": "FREE Stay & Play (Under 5s)",
            "description": "Weekdays 12:30-3:30pm term time. Interactive water feature summer.",
            "start": None,
            "url": "https://www.towerhamlets.gov.uk/lgnl/leisure_and_culture/parks_and_open_spaces/mile_end_park.aspx",
            "address": "Mile End Park, London E3",
            "distance": "~10 mins",
            "age": "Under 5s",
            "cost": "Free",
            "category": "Soft Play & Indoor",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Polka Theatre",
            "title": "Children's Theatre (from 6 months)",
            "description": "Dedicated children's theatre, cafe, outdoor space.",
            "start": None,
            "url": "https://polkatheatre.com/whats-on/",
            "address": "240 The Broadway, Wimbledon SW19 1SB",
            "distance": "~75 mins",
            "age": "6 months+",
            "cost": "£8-15",
            "category": "Theatre & Shows",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Puppet Theatre Barge",
            "title": "Puppet Shows on a Barge",
            "description": "Unique puppet shows in Little Venice / Richmond. 50-seat intimate venue.",
            "start": None,
            "url": "https://www.puppetbarge.com/",
            "address": "Little Venice, London W2 / Richmond",
            "distance": "~50 mins",
            "age": "Ages 3-7",
            "cost": "£12-15",
            "category": "Theatre & Shows",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Half Moon Theatre",
            "title": "Children's Theatre",
            "description": "Theatre for young audiences in Limehouse.",
            "start": None,
            "url": "https://www.halfmoon.org.uk/whats-on/",
            "address": "43 White Horse Rd, London E1 0ND",
            "distance": "~15 mins",
            "age": "All ages",
            "cost": "£5-12",
            "category": "Theatre & Shows",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Magic Circle",
            "title": "Family Magic Shows",
            "description": "Magic workshops and shows for families.",
            "start": None,
            "url": "https://themagiccircle.co.uk/",
            "address": "12 Stephenson Way, London NW1 2HD",
            "distance": "~40 mins",
            "age": "All ages",
            "cost": "Check venue",
            "category": "Theatre & Shows",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Big Little Fun",
            "title": "Under-5s Soft Play",
            "description": "Designed for under-5s: role play, arts & crafts, soft climbing.",
            "start": None,
            "url": "https://biglittlefun.co.uk/",
            "address": "Greenwich, London SE10",
            "distance": "~40 mins",
            "age": "Under 5s",
            "cost": "From £5.50",
            "category": "Soft Play & Indoor",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Lee Valley Ice Centre",
            "title": "Family Skating Sessions",
            "description": "Two Olympic-sized rinks, learn to skate from age 4.",
            "start": None,
            "url": "https://www.visitleevalley.org.uk/ice",
            "address": "Lea Bridge Rd, London E10 7QL",
            "distance": "~25 mins",
            "age": "4+",
            "cost": "From £10",
            "category": "Sports & Swimming",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Regent's Canal Boat Trips",
            "title": "Little Venice to Camden",
            "description": "45-min boat trips passing London Zoo. Under-3s free.",
            "start": None,
            "url": "https://www.londonwaterbus.com/",
            "address": "Little Venice / Camden Lock",
            "distance": "~45 mins",
            "age": "All ages",
            "cost": "Under 3s free, children £14",
            "category": "Outdoor & Parks",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Wingham Wildlife Park",
            "title": "Wildlife Park Day Out",
            "description": "Farm animals, exotic species, dinosaur exhibit.",
            "start": None,
            "url": "https://www.winghamwildlifepark.co.uk/",
            "address": "Rusham Rd, Wingham, Canterbury CT3 1JL",
            "distance": "~90 mins drive",
            "age": "All ages",
            "cost": "££",
            "category": "Farms & Animals",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Old MacDonald's Farm",
            "title": "Family Farm Visit",
            "description": "Petting zoo, pony rides, tractor rides, outdoor play.",
            "start": None,
            "url": "https://www.oldmacdonaldsfarm.co.uk/",
            "address": "Weald Country Park, Brentwood CM14 5QS",
            "distance": "~60 mins",
            "age": "All ages",
            "cost": "££",
            "category": "Farms & Animals",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Jess Jos Pottery",
            "title": "Pottery Classes",
            "description": "Pottery painting and clay sessions for families.",
            "start": None,
            "url": "https://jessjos.com/collections/classes",
            "address": "Bow, London E3",
            "distance": "~5 mins",
            "age": "3+",
            "cost": "From £15",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Bonbon Pottery",
            "title": "Family Pottery Sessions",
            "description": "Pottery painting for kids and families.",
            "start": None,
            "url": "https://www.bonbonpottery.co.uk/",
            "address": "East London",
            "distance": "~20 mins",
            "age": "3+",
            "cost": "From £15",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "All Star Lanes",
            "title": "Family Bowling",
            "description": "Bowling with bumpers for kids. Multiple locations.",
            "start": None,
            "url": "https://www.allstarlanes.co.uk/",
            "address": "Various London locations",
            "distance": "Varies",
            "age": "All ages",
            "cost": "££",
            "category": "Soft Play & Indoor",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Walthamstow Pumphouse Museum",
            "title": "Family Sundays",
            "description": "Local history museum, occasional family events on Sundays.",
            "start": None,
            "url": "https://www.walthamstowpumphousemuseum.org.uk/",
            "address": "10 South Access Rd, London E17 8AX",
            "distance": "~35 mins",
            "age": "All ages",
            "cost": "Free",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "RHS Hyde Hall",
            "title": "Family Garden Visits",
            "description": "Seasonal family trails and workshops. Check website for events.",
            "start": None,
            "url": "https://www.rhs.org.uk/gardens/hyde-hall",
            "address": "Creephedge Ln, Chelmsford CM3 8ET",
            "distance": "~70 mins drive",
            "age": "All ages",
            "cost": "Members free / ££",
            "category": "Outdoor & Parks",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Ice Rink Canary Wharf",
            "title": "Covered Ice Skating (Oct-Feb)",
            "description": "Seasonal covered rink, skating aids for kids.",
            "start": None,
            "url": "https://icerinkcanarywharf.co.uk/",
            "address": "Canada Square Park, Canary Wharf E14",
            "distance": "~25 mins",
            "age": "4+",
            "cost": "From £13.50",
            "category": "Seasonal",
            "source": "Static",
            "is_new": False,
        },
        {
            "venue": "Discover Story Centre",
            "title": "Interactive Story Adventures",
            "description": "Temporarily closed, reopening mid-2026. Pop-up at Stratford Centre (free).",
            "start": None,
            "url": "https://discover.org.uk/",
            "address": "383-387 High St, London E15 4QZ",
            "distance": "~20 mins",
            "age": "Under 8s",
            "cost": "Check venue",
            "category": "Museums & Learning",
            "source": "Static",
            "is_new": False,
        },
    ]
